AgendaTarefas/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;

namespace AgendaTarefas.Models
{
    //Herdar de DbContext usando o Microsoft.EntityFrameworkCore
    public class Contexto : DbContext
    {
        public DbSet<Tarefa> Tarefas { get; set; }

        //Criando um construtor, o contexto. E passando ele pelo construtor `base` como opcoes.
        public Contexto(DbContextOptions<Contexto> opcoes):base(opcoes)
        {
            //Configuração da ConnectionString em appsettings.json, este mostra a Visual Studio qual o nome do nosso banco de dados.
            
            
        }
    }
}

AgendaTarefas/Models/DatasViewModel.cs
//Aula3: Criação de uma ViewModel para nos auxiliar na manipulação das Datas.

namespace AgendaTarefas.Models
{
	public class DatasViewModel
	{
		public string? Datas { get; set; }

		public string? Identificadores { get; set; }

	}
}

AgendaTarefas/Models/ErrorViewModel.cs
namespace AgendaTarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendaTarefas/Models/Tarefa.cs
using System.ComponentModel.DataAnnotations;

namespace AgendaTarefas.Models
{
    public class Tarefa
    {
        public int TarefaId { get; set; }

        //Criando DataAnnotations, eles servem para personalizar os nosso dados.
        //Exemplo: Se eu quiser que o nome seja obrigatório, devo colocar [Require]
        [Required(ErrorMessage = "{0} é obrigatório.")]
        [StringLength(25, ErrorMessage = "Use menos caracteres.")]
        public string Nome { get; set; }

        public string Data { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório.")]
        [DataType(DataType.Time)]
        public string Horario { get; set; }
    }
}

AgendaTarefas/Controllers/HomeController.cs
using AgendaTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AgendaTarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgendaTarefas/Controllers/TarefasController.cs
//Aula3: Controller e Datas
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using AgendaTarefas.Models;

namespace AgendaTarefas.Controllers
{
    public class TarefasController : Controller
    {
        private readonly Contexto _contexto;

        public TarefasController(Contexto contexto)
        {
            _contexto = contexto;
        }
        public IActionResult Index()
        {
            return View(PegarDatas());
        }

        private List<DatasViewModel> PegarDatas()
        {
            DateTime dataAtual = DateTime.Now;
            DateTime dataLimite = DateTime.Now.AddDays(10);
            int qtdDias = 0;
            DatasViewModel data;
            List<DatasViewModel> listaDatas = new List<DatasViewModel>();

            while (dataAtual < dataLimite)
            {
                data = new DatasViewModel();
                data.Datas = dataAtual.ToShortDateString();
                data.Identificadores = "collapse" + dataAtual.ToShortDateString().Replace("/", "");
                listaDatas.Add(data);
                qtdDias = qtdDias + 1;
                dataAtual = DateTime.Now.AddDays(qtdDias);
            }

            return listaDatas;
        }

        //Criar Tarefas: Aula 6
        [HttpGet]
        public IActionResult CriarTarefa(string dataTarefa)
        {
            Tarefa tarefa = new Tarefa
            {
                Data = dataTarefa
            };

            return View(tarefa);
        }
        [HttpPost]
        public async Task<IActionResult> CriarTarefa(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                _contexto.Tarefas.Add(tarefa);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }
        //Atualizar Tarefas: Aula 8
        [HttpGet]
        public async Task<IActionResult> AtualizarTarefa(int tarefaId)
        {
            Tarefa tarefa = await _contexto.Tarefas.FindAsync(tarefaId);

            if (tarefa == null)
                return NotFound();

            return View(tarefa);
        }

        [HttpPost]
        public async Task<IActionResult> AtualizarTarefa(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                _contexto.Update(tarefa);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }

        //Aula 10: Exclusão de Tarefas(Por ser exclusão ele só possui o Post!)
        //Observasão: A exclusão será feita em Ajax!

        //Precisa do ID da tarefa(int tarefaId), para identificar qual tarefas queremos excluir! 
        [HttpPost]
        public async Task<JsonResult> ExcluirTarefa(int tarefaId)
        {
            //Pegando a Tarefa
            Tarefa tarefa = await _contexto.Tarefas.FindAsync(tarefaId);
            //Removendo a Tarefa
            _contexto.Tarefas.Remove(tarefa);
            //Salvando a transação no banco de dados
            await _contexto.SaveChangesAsync();
            return Json(true);
        }

    }
}

AgendaTarefas/ViewComponents/ListaTarefasViewComponent.cs
using AgendaTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AgendaTarefas.ViewComponents
{
    public class ListaTarefasViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;

        //Criando o Construtor e inicializa-lo via injeção de dependências.
        public ListaTarefasViewComponent(Contexto contexto)
        {
            _contexto = contexto;
        }

        //IViewComponent é um método obrigatório.
        public async Task<IViewComponentResult> InvokeAsync(string data)
        {
            return View(await _contexto.Tarefas.OrderBy(t => t.Horario).Where(t => t.Data == data).ToListAsync());
        }

    }
}

AgendaTarefas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AgendaTarefas/Views/Shared/Components/ListaTarefas/Default.cshtml
@model IEnumerable<AgendaTarefas.Models.Tarefa>

@{
    Layout = null;
}

<div class="border border-light shadow rounded rounded-lg p-4">
    @if (Model.Count() > 0)
    {
        <ul class="list-group">
            @foreach (var item in Model)
            {
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-2">
                            <span class="badge bg-success">@Html.DisplayFor(modelItem => item.Horario)</span>
                        </div>

                        <div class="col-6">
                            @Html.DisplayFor(modelItem => item.Nome)
                        </div>

                        <div class="col-4">
                            <a asp-action="AtualizarTarefa" asp-route-tarefaId="@item.TarefaId" class="btn btn-sm btn-outline-primary rounded-circle">
                                <i class="fa fa-pencil-square-o"></i>

                            </a>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-sm btn-outline-danger rounded-circle" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="ConfirmarExclusao(@item.TarefaId, '@item.Nome')">
                                <i class="fa fa-trash"></i>
                            </button>
                        </div>
                    </div>
                </li>
            }
        </ul>
    }
    else
    {
        <p class="alert alert-warning">Sem tarefas ainda</p>
    }
</div>

AgendaTarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendaTarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    @*Link dos Icons in 4.7: https://fontawesome.com/v4/icons/*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgendaTarefas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgendaTarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AgendaTarefas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AgendaTarefas/Views/Tarefas/AtualizarTarefa.cshtml
@model AgendaTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Atualizar tarefa na data " + Model.Data;
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <text class="card-header">Atualizar tarefa na data @Model.Data</text>
                <form asp-action="AtualizarTarefa">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="TarefaId" />

                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>

                        <input asp-for="Data" class="form-control" type="hidden" />

                        <div class="form-group">
                            <label asp-for="Horario" class="control-label"></label>
                            <input asp-for="Horario" class="form-control" />
                            <span asp-validation-for="Horario" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="form-group">
                            <a asp-action="Index" class="btn btn-sm btn-outline-secondary rounded-square">
                                <i class="fa fa-arrow-circle-o-left"></i> Voltar
                            </a>
                            <button type="submit" value="Atualizar" class="btn btn-sm btn-outline-primary rounded-square">
                                <i class="fa fa-refresh"></i> Atualizar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AgendaTarefas/Views/Tarefas/CriarTarefa.cshtml
@model AgendaTarefas.Models.Tarefa

@{
    ViewData["Title"] = " Nova tarefa na data " + Model.Data;
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <text class="card-header">Nova tarefa na data @Model.Data</text>
                <form asp-action="CriarTarefa">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>

                        <input asp-for="Data" type="hidden" />

                        <div class="form-group">
                            <label asp-for="Horario" class="control-label"></label>
                            <input asp-for="Horario" class="form-control" />
                            <span asp-validation-for="Horario" class="text-danger"></span>
                        </div>
                        &emsp;
                        <div class="card-footer">
                            <div class="form-group">
                                <a asp-action="Index" class="btn btn-sm btn-outline-secondary rounded-square">
                                    <i class="fa fa-arrow-circle-o-left"></i> Voltar
                                </a>

                                <button type="submit" value="Salvar" class="btn btn-sm btn-outline-primary rounded-square" >
                                    <i class="fa fa-floppy-o"></i> Salvar
                                </button>
                            </div>

                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

AgendaTarefas/Views/Tarefas/Index.cshtml
@model IEnumerable<AgendaTarefas.Models.DatasViewModel>

@{
    ViewData["Title"] = "Tarefas Cadastradas";
}


@foreach (var item in Model)
{
    <div class="accordion" id="painelTarefas">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-10">
                        <a class="btn btn-sm btn-outline-primary rounded-circle" href="#@item.Identificadores" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="@item.Identificadores">
                            <i class="fa fa-sm fa-chevron-down"></i>
                        </a>
                        &emsp;
                        <i class="fa fa-calendar"></i> @item.Datas
                    </div>
                    <div class="col-2">
                        <a asp-action="CriarTarefa" asp-route-dataTarefa="@item.Datas" class="btn btn-sm btn-outline-dark">Nova Tarefa</a>
                    </div>
                </div>
            </div>

            <div id="@item.Identificadores" class="collapse" data-parent="#painelTarefas">
                <div class="card-body">
                    @await Component.InvokeAsync("ListaTarefas", item.Datas)
                </div>
            </div>
        </div>
    </div>
}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação de Exclusão</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Prosseguir com a exclusão da tarefa: <text class="nomeTarefa"></text> ? </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-outline-secondary btnFechar" data-bs-dismiss="modal">Não</button>
                <a href="#" class="btn btn-sm btn-danger rounded-square btnExcluir">
                    Sim
                </a>
            </div>
        </div>
    </div>
</div>

@*Criando uma seção de Scripts*@
@section Scripts {
    <script>
        function ConfirmarExclusao(tarefaId, nomeTarefa) {
            $(".nomeTarefa").text(nomeTarefa);
            $(".modal").modal();
            $(".btnExcluir").on('click', function() {
                $.ajax({
                    url: 'Tarefas/ExcluirTarefa',
                    method: 'POST',
                    data: { tarefaId: tarefaId },
                    success: function(data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }
                });
            });
            $('.btnFechar').on('click', function() {
                tarefaId = null;
                nomeTarefa = null;
                $(".modal").modal('hide');
            });
        }
    </script>
}